name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest #
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' #

      - name: Install Linting Tools
        run: pip install flake8 black isort

      - name: Run flake8
        run: flake8 . --exclude=migrations

      - name: Run black check
        run: black --check .

      - name: Run isort check
        run: isort --check-only .
